version: "3.9"

networks:
  cynett-network:
    name: cynett-network
    driver: bridge

services:
  app:
    build: .
    command: yarn start
    container_name: app
    restart: always
    env_file:
      - .env.prod
    ports:
      - 4000:4000
    networks:
      - cynett-network
    depends_on:
      - redis
      - mongo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  redis:
    image: "bitnami/redis:latest"
    container_name: cynett-redis
    restart: always
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=false
      - REDIS_PASSWORD=1234
    networks:
      - cynett-network

  mongo:
    image: mongo:4.2
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - cynett-network
    environment:
      MONGO_INITDB_DATABASE: Cynett
      MONGO_INITDB_ROOT_USERNAME: Cynett
      MONGO_INITDB_ROOT_PASSWORD: Cynett
    volumes:
      - .:/usr/mongo/data
