version: '3.9'

networks:
  cynett-network:
    name: cynett-network
    driver: bridge

services:
  app:
    build: .
    command: yarn start
    container_name: app
    restart: always
    env_file:
      - .env
    ports:
      - 4000:4000
    networks:
      - cynett-network
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'

  redis:
    image: 'bitnami/redis:latest'
    container_name: cynett-redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=false
      - REDIS_PASSWORD=1234
    networks:
      - cynett-network
    volumes:
      - ./.redis-data:/bitnami/redis/data
